url: http://jobconnect.ethercourt.ml #https://ammimarketic.github.io
baseurl: / # /agency-jekyll-theme/

# Site settings
title: Job Connect # AMMI MarkeTIC
email: jobconnect@ethercourt.ml # abdoulayedoucoure.ammi@gmail.com
description: "Services IA pour la gestion des talents : Formations, chatbots, et plus" # VOTRE AGENCE DE MARKETING CONVERSATIONNEL avec une équipe d’experts spécialisée dans le web et l’IA. Obtenez une présence digitale complète - Simple et Rapide ! Nos délais de livraison d'une semaine par étape peuvent être accélérés à votre demande."


# Team names, titles and social links
people:
- name: Recruteur
  pic: message-bot # download bots-brands-solid.svg 1
  position: Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    # - title: linkedin
      # url: https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Edition Premium # Ethercourt Machine Learning
  pic: 2
  position: Couverture souple
  social:
    - title: book # twitter
      url: shop.ethercourt.ml # https://twitter.com/ethercourt
    - title: amazon # facebook
      url: # https://www.facebook.com/ethercourt/
    # - title: linkedin
      # url: https://www.linkedin.com/company/ethercourt/

- name: Edition Entreprise # Synergie PoC-compétences
  pic: BookBrushImage5059
  position: Couverture rigide # Guide pour aligner la validation de concept sur les besoins réels en compétences
  social:
    - title: book # tablet
      url: 
    - title: amazon
      url: 
    # - title: facebook
      # url: 


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AmmiMarketic
  - title: facebook
    url: https://www.facebook.com/ammimarketic
  - title: linkedin
    url: https://www.linkedin.com/showcase/ammi-marketic
  - title: github
    url:  https://github.com/AMMIMarkeTIC
    

# Postal address (add as many lines as necessary)
address:
  - line: BKO
  - line: PAR

# Build settings
markdown: kramdown
permalink: pretty
