url: http://livre.ethercourt.ml #https://ammimarketic.github.io
baseurl: / # /agency-jekyll-theme/

# Site settings
title: Les Relations Investisseurs x l'IA # AMMI MarkeTIC
email: livre@ethercourt.ml # abdoulayedoucoure.ammi@gmail.com
description: "Guide pratique pour lever des fonds plus efficacement grâce à l'Intelligence Artificielle" # VOTRE AGENCE DE MARKETING CONVERSATIONNEL avec une équipe d’experts spécialisée dans le web et l’IA. Obtenez une présence digitale complète - Simple et Rapide ! Nos délais de livraison d'une semaine par étape peuvent être accélérés à votre demande."


# Team names, titles and social links
people:
- name: Chatbot Relations Investisseurs
  pic: message-bot # download bots-brands-solid.svg 1
  position: Chatbot de base # Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/c/33605861568 # https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Anticiper les questions
  pic: message-bot # download bots-brands-solid.svg 1
  position: Extension IA
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Préparer la Documentation
  pic: message-bot # download bots-brands-solid.svg 1
  position: Extension IA # Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Développer un plan stratégique convaincant
  pic: message-bot # download bots-brands-solid.svg 1
  position: Extension IA # Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Identifier le meilleur moment pour vendre
  pic: message-bot # download bots-brands-solid.svg 1
  position: Extension IA # Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Créer Votre Business Plan
  pic: message-bot # download bots-brands-solid.svg 1
  position: Extension IA
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Rédiger les courriers de prise de contact avec les investisseurs
  pic: message-bot # download bots-brands-solid.svg 1
  position: Extension IA # Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Faire des simulations d'entretiens avec les investisseurs
  pic: message-bot # download bots-brands-solid.svg 1
  position: Extension IA # Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Découvrir comment transformer votre entreprise
  pic: message-bot # download bots-brands-solid.svg 1
  position: Extension IA # Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
    # url: https://twitter.com/AmmiMarketic
  - title: facebook
    url: https://www.facebook.com/monjobconnect # https://www.facebook.com/ammimarketic
  # - title: linkedin
    # url: https://www.linkedin.com/showcase/ammi-marketic
  - title: github
    url:  https://github.com/jobconnectml/ # https://github.com/AMMIMarkeTIC
  - title: amazon
    url:  https://www.amazon.fr/Relations-Investisseurs-assist%C3%A9es-par-conversationnelle/dp/B0D5WJQS5C#:~:text=%22Les%20Relations%20Investisseurs%20assist%C3%A9es%20par%20l'IA%22%20est%20la,gr%C3%A2ce%20%C3%A0%20l'IA%20conversationnelle.
    

# Postal address (add as many lines as necessary)
address:
  - line: BKO
  - line: PAR

# Build settings
markdown: kramdown
permalink: pretty
