url: https://emlpublishing.github.io
baseurl: / # /agency-jekyll-theme/

# Site settings
title: Se financer avec l'IA # AMMI MarkeTIC
email: sefinancer@ethercourt.ml # abdoulayedoucoure.ammi@gmail.com
description: "Guide pratique pour lever des fonds plus efficacement grâce à l'Intelligence Artificielle" # VOTRE AGENCE DE MARKETING CONVERSATIONNEL avec une équipe d’experts spécialisée dans le web et l’IA. Obtenez une présence digitale complète - Simple et Rapide ! Nos délais de livraison d'une semaine par étape peuvent être accélérés à votre demande."


# Team names, titles and social links
people:
- name: Assistant IA Business Plan
  pic: message-bot # download bots-brands-solid.svg 1
  position: Avec la version Premium de notre chatbot, créez un business plan complet en un clin d'œil grâce à des conseils personnalisés et un processus guidé. <br>Pour votre communauté, la version Entreprise, personnalisée à votre image, permet à vos utilisateurs de bénéficier du même accompagnement.
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/

- name: Assistant IA Relations Investisseurs
  pic: message-bot # download bots-brands-solid.svg 1
  position: La version Premium vous permet de vous former à l’investissement à votre rythme, tandis que la version Entreprise, directement connectée à vos informations, segmente et guide vos investisseurs jusqu'à vous. <br>Laissez l’IA gérer les potentiels investisseurs pendant que vous vous concentrez sur l'intégration des plus pertinents.
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/c/33605861568 # https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/

- name: Autres assistants IA sur mesure
  pic: message-bot # download bots-brands-solid.svg 1
  position: Préparer une <strong>Due diligence</strong><br>Développer un <strong>plan</strong> stratégique convaincant<br>Identifier le <strong>meilleur</strong> moment pour lever des fonds<br><strong>Contacter </strong> les investisseurs<br>Simuler des <strong>entretiens</strong> avec les investisseurs<br><strong>Automatiser</strong> votre entreprise
  
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/c/33605861568 # https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


# - name: Anticiper les questions
#   pic: message-bot # download bots-brands-solid.svg 1
#   position: Le chatbot fournit un feedback immédiat à l'entrepreneur, l'aidant à affiner son discours et à gagner en confiance.
#   social:
#     - title: comments #book bots code
#       url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
#     - title: code # amazon
#       url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
#     - title: whatsapp
#       url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/

# - name: Préparer la Due diligence
#   pic: message-bot # download bots-brands-solid.svg 1
#   position: Le chatbot est capable d'identifier les potentiels risques juridiques, financiers ou opérationnels en comparant les informations extraites avec les bases de données.
#   social:
#     - title: comments #book bots code
#       url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
#     - title: code # amazon
#       url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
#     - title: whatsapp
#       url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/

# - name: Développer un plan stratégique convaincant
#   pic: message-bot # download bots-brands-solid.svg 1
#   position: Il peut aider à structurer le plan stratégique en proposant une logique cohérente et en identifiant les étapes clés.
#   social:
#     - title: comments #book bots code
#       url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
#     - title: code # amazon
#       url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
#     - title: whatsapp
#       url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/

# - name: Identifier le meilleur moment pour vendre
#   pic: message-bot # download bots-brands-solid.svg 1
#   position: Identifier le meilleur moment pour lever des fonds est une décision stratégique cruciale pour toute entreprise.
#   social:
#     - title: comments #book bots code
#       url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
#     - title: code # amazon
#       url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
#     - title: whatsapp
#       url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
    # url: https://twitter.com/AmmiMarketic
  - title: facebook
    url: https://www.facebook.com/monjobconnect # https://www.facebook.com/ammimarketic
  - title: linkedin
    url: https://www.linkedin.com/showcase/les-relations-investisseurs-assist%C3%A9es-par-l%E2%80%99ia/?trk=public_post-text
  - title: github
    url:  https://github.com/jobconnectml/ # https://github.com/AMMIMarkeTIC
  - title: amazon
    url:  https://www.amazon.fr/Relations-Investisseurs-assist%C3%A9es-par-conversationnelle/dp/B0D5WJQS5C#:~:text=%22Les%20Relations%20Investisseurs%20assist%C3%A9es%20par%20l'IA%22%20est%20la,gr%C3%A2ce%20%C3%A0%20l'IA%20conversationnelle.
    

# Postal address (add as many lines as necessary)
address:
  - line: BKO
  - line: PAR

# Build settings
markdown: kramdown
permalink: pretty
